const PEOPLE = [
    {
      id: 0,
      name: 'Aria',
      sex: 'girl'
    }, {
      id: 1,
      name: 'Logan',
      sex: 'boy'
    }, {
      id: 2,
      name: 'Quinn',
      sex: 'girl'
    }, {
      id: 3,
      name: 'Kai',
      sex: 'boy'
    }, {
      id: 4,
      name: 'Dashiell',
      sex: 'boy'
    }, {
      id: 5,
      name: 'John',
      sex: 'boy'
    }, {
      id: 6,
      name: 'Seraphina',
      sex: 'girl'
    }, {
      id: 7,
      name: 'Caroline',
      sex: 'girl'
    }, {
      id: 8,
      name: 'Tobias',
      sex: 'boy'
    }, {
      id: 9,
      name: 'Harper',
      sex: 'girl'
    }, {
      id: 10,
      name: 'Mabe',
      sex: 'girl'
    }, {
      id: 11,
      name: 'Iris',
      sex: 'girl'
    }, {
      id: 12,
      name: 'Beatrice',
      sex: 'girl'
    }, {
      id: 13,
      name: 'Knox',
      sex: 'boy'
    }, {
      id: 14,
      name: 'August',
      sex: 'boy'
    }, {
      id: 15,
      name: 'Poppy',
      sex: 'girl'
    }, {
      id: 16,
      name: 'Aurora',
      sex: 'girl'
    }, {
      id: 17,
      name: 'Wyatt',
      sex: 'boy'
    }, {
      id: 18,
      name: 'Ezra',
      sex: 'boy'
    }, {
      id: 19,
      name: 'Emily',
      sex: 'girl'
    }, {
      id: 20,
      name: 'Sebastian',
      sex: 'boy'
    }, {
      id: 21,
      name: 'Gabriel',
      sex: 'boy'
    }, {
      id: 22,
      name: 'Charlie',
      sex: 'boy'
    }, {
      id: 23,
      name: 'Isabella',
      sex: 'girl'
    }, {
      id: 24,
      name: 'Elliot',
      sex: 'boy'
    }, {
      id: 25,
      name: 'Declan',
      sex: 'boy'
    }, {
      id: 26,
      name: 'Benjamin',
      sex: 'boy'
    }, {
      id: 27,
      name: 'Gemma',
      sex: 'girl'
    }, {
      id: 28,
      name: 'Lucas',
      sex: 'boy'
    }, {
      id: 29,
      name: 'Chloe',
      sex: 'girl'
    }, {
      id: 30,
      name: 'Khaleesi',
      sex: 'girl'
    }, {
      id: 31,
      name: 'Austin',
      sex: 'boy'
    }, {
      id: 32,
      name: 'Matilda',
      sex: 'girl'
    }, {
      id: 33,
      name: 'Grayson',
      sex: 'boy'
    }, {
      id: 34,
      name: 'Beckett',
      sex: 'boy'
    }, {
      id: 35,
      name: 'Nicholas',
      sex: 'boy'
    }, {
      id: 36,
      name: 'Ronan',
      sex: 'boy'
    }, {
      id: 37,
      name: 'Eliza',
      sex: 'girl'
    }, {
      id: 38,
      name: 'Imogen',
      sex: 'girl'
    }, {
      id: 39,
      name: 'Amelia',
      sex: 'girl'
    }, {
      id: 40,
      name: 'Nathaniel',
      sex: 'boy'
    }, {
      id: 41,
      name: 'Ryker',
      sex: 'boy'
    }
  ];

  export default PEOPLE;